/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package file;

import java.sql.DriverManager;
import java.text.DecimalFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;
import javax.swing.JOptionPane;


/**
 *
 * @author ThinkPad
 */
public class b_menu extends javax.swing.JFrame {

    int harga1, harga2, harga3, harga4, harga5, harga6, harga7, harga8, harga9, harga10;
    int jml1, jml2, jml3, jml4, jml5, jml6, jml7, jml8, jml9, jml10;
    int total1, total2, total3, total4, total5, total6, total7, total8, total9, total10;
    /**
     * Creates new form b_menu
     */
    public b_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txttgl = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtjmlesteh = new javax.swing.JTextField();
        txtjmlesjer = new javax.swing.JTextField();
        txtjmlesdgn = new javax.swing.JTextField();
        txtjmltehagt = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtharesteh = new javax.swing.JTextField();
        txtharesjer = new javax.swing.JTextField();
        txtharesdgn = new javax.swing.JTextField();
        txtharteagt = new javax.swing.JTextField();
        txttotharga = new javax.swing.JTextField();
        txtnmpemesan = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblmibi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtjmlmibi = new javax.swing.JTextField();
        txtjmlmiker = new javax.swing.JTextField();
        txtjmlmiso = new javax.swing.JTextField();
        txtjmlbabi = new javax.swing.JTextField();
        txtjmlbasu = new javax.swing.JTextField();
        txtjmlbalur = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtharmibi = new javax.swing.JTextField();
        txtharmiker = new javax.swing.JTextField();
        txtharmiso = new javax.swing.JTextField();
        txtharbabi = new javax.swing.JTextField();
        txtharbasu = new javax.swing.JTextField();
        txtharbalur = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        txtloginsbg = new javax.swing.JTextField();
        btnhitungdm = new javax.swing.JButton();
        btncetakdm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnbataldm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btndata = new javax.swing.JButton();
        btnkeluardm = new javax.swing.JButton();
        btnok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Pesanan");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel33.setText("Kembalian");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setText("DATA MENU");

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Menu Minuman");

        jLabel22.setText("Es Teh");

        jLabel23.setText("Es Jeruk");

        jLabel24.setText("Es Degan");

        jLabel25.setText("Teh Anget");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel35.setText("Jumlah");

        txtjmlesteh.setText("0");

        txtjmlesjer.setText("0");

        txtjmlesdgn.setText("0");

        txtjmltehagt.setText("0");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel36.setText("Harga");

        txtharesteh.setText("3000");
        txtharesteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharestehActionPerformed(evt);
            }
        });

        txtharesjer.setText("3000");
        txtharesjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharesjerActionPerformed(evt);
            }
        });

        txtharesdgn.setText("4000");
        txtharesdgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharesdgnActionPerformed(evt);
            }
        });

        txtharteagt.setText("3000");
        txtharteagt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharteagtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtharesteh)
                        .addComponent(txtharesjer)
                        .addComponent(txtharesdgn)
                        .addComponent(txtharteagt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel36)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(txtjmlesteh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjmlesjer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjmlesdgn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjmltehagt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjmlesteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjmlesjer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjmlesdgn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjmltehagt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtharesteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtharesjer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtharesdgn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtharteagt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Menu Makanan");

        lblmibi.setText("Mie Ayam Biasa ");

        jLabel7.setText("Mie Ayam Ceker");

        jLabel8.setText("Mie Ayam Bakso");

        jLabel9.setText("Bakso Biasa");

        jLabel10.setText("Bakso Super");

        jLabel11.setText("Bakso Telur");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Jumlah");

        txtjmlmibi.setText("0");
        txtjmlmibi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlmibiActionPerformed(evt);
            }
        });

        txtjmlmiker.setText("0");

        txtjmlmiso.setText("0");

        txtjmlbabi.setText("0");

        txtjmlbasu.setText("0");

        txtjmlbalur.setText("0");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setText("Harga");

        txtharmibi.setText("7000");
        txtharmibi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharmibiActionPerformed(evt);
            }
        });

        txtharmiker.setText("10000");
        txtharmiker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharmikerActionPerformed(evt);
            }
        });

        txtharmiso.setText("10000");
        txtharmiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharmisoActionPerformed(evt);
            }
        });

        txtharbabi.setText("8000");
        txtharbabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharbabiActionPerformed(evt);
            }
        });

        txtharbasu.setText("12000");
        txtharbasu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharbasuActionPerformed(evt);
            }
        });

        txtharbalur.setText("10000");
        txtharbalur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharbalurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(24, 24, 24))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel7)
                                .addComponent(lblmibi))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel29))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtharmibi)
                        .addComponent(txtharmiker)
                        .addComponent(txtharmiso)
                        .addComponent(txtharbabi)
                        .addComponent(txtharbasu)
                        .addComponent(txtharbalur, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjmlmibi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjmlmiker, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjmlmiso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjmlbabi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjmlbasu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjmlbalur, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel19)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharmibi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharmiker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharmiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharbabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharbasu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharbalur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmibi)
                            .addComponent(txtjmlmibi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtjmlmiker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtjmlmiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtjmlbabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtjmlbasu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtjmlbalur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnhitungdm.setText("Hitung");
        btnhitungdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungdmActionPerformed(evt);
            }
        });

        btncetakdm.setText("Cetak");
        btncetakdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakdmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Tanggal ");

        btnbataldm.setText("Batal");
        btnbataldm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbataldmActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nama Pemesan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Log in as");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setText("Total Harga");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setText("Bayar");

        btndata.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btndata.setText("Data");
        btndata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndataActionPerformed(evt);
            }
        });

        btnkeluardm.setText("Keluar");
        btnkeluardm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluardmActionPerformed(evt);
            }
        });

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(txtloginsbg, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttgl)
                                    .addComponent(txtnmpemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnkeluardm)))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btncetakdm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txttotharga, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnbataldm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnhitungdm, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(98, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btndata)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel37)
                .addGap(33, 33, 33)
                .addComponent(btndata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtloginsbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkeluardm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnmpemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txttotharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhitungdm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncetakdm)
                    .addComponent(btnok))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbataldm))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndataActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new c_transaksi().setVisible(true);
    }//GEN-LAST:event_btndataActionPerformed

    private void btncetakdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakdmActionPerformed
        // TODO add your handling code here:
        int kembali = Integer.parseInt(txtbayar.getText());
        int total = kembali - (total1+total2+total3+total4+total5+total6+total7+total8+total9+total10);
        
        txtkembalian.setText("Rp. "+Integer.toString(total));
        
    }//GEN-LAST:event_btncetakdmActionPerformed

    private void btnbataldmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbataldmActionPerformed
        // TODO add your handling code here:
       
        txtjmlbabi.setText("");
        txtjmlbalur.setText("");
        txtjmlbasu.setText("");
        txtjmlesdgn.setText("");
        txtjmlesjer.setText("");
        txtjmlesteh.setText("");
        txtjmltehagt.setText("");
        txtjmlmibi.setText("");
        txtjmlmiker.setText("");
        txtjmlmiso.setText("");
        
        
        txtloginsbg.setText(null);
        txtnmpemesan.setText("");
        txttgl.setText(null);
        txtbayar.setText("");
        txtkembalian.setText("");
        txttotharga.setText("");
        
    }//GEN-LAST:event_btnbataldmActionPerformed

    private void btnkeluardmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluardmActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        txtloginsbg.setText("");
    }//GEN-LAST:event_btnkeluardmActionPerformed

    private void btnhitungdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungdmActionPerformed
        // TODO add your handling code here:
        harga1 = Integer.parseInt(txtharmibi.getText());
        jml1 = Integer.parseInt(txtjmlmibi.getText());
        harga2 = Integer.parseInt(txtharmiker.getText());
        jml2 = Integer.parseInt(txtjmlmiker.getText());
        harga3 = Integer.parseInt(txtharmiso.getText());
        jml3 = Integer.parseInt(txtjmlmiso.getText());
        harga4 = Integer.parseInt(txtharbabi.getText());
        jml4 = Integer.parseInt(txtjmlbabi.getText());
        harga5 = Integer.parseInt(txtharbasu.getText());
        jml5 = Integer.parseInt(txtjmlbasu.getText());
        harga6 = Integer.parseInt(txtharbalur.getText());
        jml6 = Integer.parseInt(txtjmlbalur.getText());
        harga7 = Integer.parseInt(txtharesteh.getText());
        jml7 = Integer.parseInt(txtjmlesteh.getText());
        harga8 = Integer.parseInt(txtharesjer.getText());
        jml8 = Integer.parseInt(txtjmlesjer.getText());
        harga9 = Integer.parseInt(txtharesdgn.getText());
        jml9 = Integer.parseInt(txtjmlesdgn.getText());
        harga10 = Integer.parseInt(txtharteagt.getText());
        jml10 = Integer.parseInt(txtjmltehagt.getText());
        
        total1 = harga1 * jml1;
        total2 = harga2 * jml2;
        total3 = harga3 * jml3;
        total4 = harga4 * jml4;
        total5 = harga5 * jml5;
        total6 = harga6 * jml6;
        total7 = harga7 * jml7;
        total8 = harga8 * jml8;
        total9 = harga9 * jml9;
        total10= harga10* jml10;
        
        DecimalFormat angka = new DecimalFormat("###,###,");
        txttotharga.setText("" + Integer.toString(total1+total2+total3+total4+total5+total6+total7+total8+total9+total10));
    }//GEN-LAST:event_btnhitungdmActionPerformed

    private void txtharestehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharestehActionPerformed
        // TODO add your handling code here:
        harga7 = Integer.parseInt(txtharesteh.getText());
        jml7 = Integer.parseInt(txtjmlesteh.getText());
        
        total7 = harga7*jml7;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharesteh.setText("" + Integer.toString(total7));
    }//GEN-LAST:event_txtharestehActionPerformed

    private void txtharesjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharesjerActionPerformed
        // TODO add your handling code here:
        harga8 = Integer.parseInt(txtharesjer.getText());
        jml8 = Integer.parseInt(txtjmlesjer.getText());
        
        total8 = harga8*jml8;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharesjer.setText("" + Integer.toString(total8));
    }//GEN-LAST:event_txtharesjerActionPerformed

    private void txtharesdgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharesdgnActionPerformed
        // TODO add your handling code here:
        harga9 = Integer.parseInt(txtharesdgn.getText());
        jml9 = Integer.parseInt(txtjmlesdgn.getText());
        
        total9 = harga9*jml9;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharesdgn.setText("" + Integer.toString(total9));
    }//GEN-LAST:event_txtharesdgnActionPerformed

    private void txtharteagtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharteagtActionPerformed
        // TODO add your handling code here:
        harga10 = Integer.parseInt(txtharteagt.getText());
        jml10 = Integer.parseInt(txtjmltehagt.getText());
        
        total10 = harga10*jml10;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharteagt.setText("" + Integer.toString(total10));
    }//GEN-LAST:event_txtharteagtActionPerformed

    private void txtharmibiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharmibiActionPerformed
        // TODO add your handling code here:
        harga1 = Integer.parseInt(txtharmibi.getText());
        jml1 = Integer.parseInt(txtjmlmibi.getText());
        
        total1 = harga1*jml1;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharmibi.setText("" + Integer.toString(total1));
    }//GEN-LAST:event_txtharmibiActionPerformed

    private void txtharmikerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharmikerActionPerformed
        // TODO add your handling code here:
        harga2 = Integer.parseInt(txtharmiker.getText());
        jml2 = Integer.parseInt(txtjmlmiker.getText());
        
        total2 = harga2*jml2;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharmiker.setText("" + Integer.toString(total2));
    }//GEN-LAST:event_txtharmikerActionPerformed

    private void txtharmisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharmisoActionPerformed
        // TODO add your handling code here:
        harga3 = Integer.parseInt(txtharmiso.getText());
        jml3 = Integer.parseInt(txtjmlmiso.getText());
        
        total3 = harga3*jml3;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharmiso.setText("" + Integer.toString(total3));
    }//GEN-LAST:event_txtharmisoActionPerformed

    private void txtharbabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharbabiActionPerformed
        // TODO add your handling code here:
        harga4 = Integer.parseInt(txtharbabi.getText());
        jml4 = Integer.parseInt(txtjmlbabi.getText());
        
        total4 = harga4*jml4;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharbabi.setText("" + Integer.toString(total4));
    }//GEN-LAST:event_txtharbabiActionPerformed

    private void txtharbasuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharbasuActionPerformed
        // TODO add your handling code here:
        harga5 = Integer.parseInt(txtharbasu.getText());
        jml5 = Integer.parseInt(txtjmlbasu.getText());
        
        total5 = harga5*jml5;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharbasu.setText("" + Integer.toString(total5));
    }//GEN-LAST:event_txtharbasuActionPerformed

    private void txtharbalurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharbalurActionPerformed
        // TODO add your handling code here:
        harga6 = Integer.parseInt(txtharbalur.getText());
        jml6 = Integer.parseInt(txtjmlbalur.getText());
        
        total6 = harga6*jml6;
        
        DecimalFormat angka = new DecimalFormat("###,###,###");
        txtharbalur.setText("" + Integer.toString(total6));
    }//GEN-LAST:event_txtharbalurActionPerformed

    private void txtjmlmibiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlmibiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlmibiActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbataldm;
    private javax.swing.JButton btncetakdm;
    private javax.swing.JButton btndata;
    private javax.swing.JButton btnhitungdm;
    private javax.swing.JButton btnkeluardm;
    private javax.swing.JButton btnok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblmibi;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharbabi;
    private javax.swing.JTextField txtharbalur;
    private javax.swing.JTextField txtharbasu;
    private javax.swing.JTextField txtharesdgn;
    private javax.swing.JTextField txtharesjer;
    private javax.swing.JTextField txtharesteh;
    private javax.swing.JTextField txtharmibi;
    private javax.swing.JTextField txtharmiker;
    private javax.swing.JTextField txtharmiso;
    private javax.swing.JTextField txtharteagt;
    private javax.swing.JTextField txtjmlbabi;
    private javax.swing.JTextField txtjmlbalur;
    private javax.swing.JTextField txtjmlbasu;
    private javax.swing.JTextField txtjmlesdgn;
    private javax.swing.JTextField txtjmlesjer;
    private javax.swing.JTextField txtjmlesteh;
    private javax.swing.JTextField txtjmlmibi;
    private javax.swing.JTextField txtjmlmiker;
    private javax.swing.JTextField txtjmlmiso;
    private javax.swing.JTextField txtjmltehagt;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtloginsbg;
    private javax.swing.JTextField txtnmpemesan;
    private javax.swing.JTextField txttgl;
    private javax.swing.JTextField txttotharga;
    // End of variables declaration//GEN-END:variables
}
